<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. data latih/data training adalah data yang digunakan untuk training model,  data validasi digunakan untuk proses validasi model dan mencegah overfitting, dan data test adalah suatu data yang digunakan untuk testing model, sebagai simulasi penggunaan model pada dunia nyata. Data testing tidak boleh pernah dilihat oleh model sebelumnya.
2. dengan cara melakukan klasifikasi, regresi dan klastering
3. Confusion matrix juga sering disebut error matrix. Pada dasarnya confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui
4. suatu library dari sklearn yang memiliki fungsi untuk menampilkan hasil klasifikasi secara lengkap kepada user

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [2]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [3]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [4]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [5]:
# Code here
x = df.drop('survival_status', axis=1)
y = df['survival_status']

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, stratify = y)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
modelKnn = KNeighborsClassifier(n_neighbors=2)

In [10]:
from sklearn.model_selection import cross_val_score

hasilScore = cross_val_score(modelKnn, x, y, cv=5)

In [11]:
hasilScore.mean()

0.6926493918561608

In [13]:
modelKnn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [20]:
y_predik = modelKnn.predict(x_train)

In [21]:
y_predik

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 2,
       1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1])

In [27]:
y_predik2 = modelKnn.predict(x_test)

In [28]:
y_predik2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1])

In [26]:
from sklearn.metrics import confusion_matrix, classification_report

confusion_matrix(y_train, y_predik, labels = [1,0])

array([[168,   0],
       [  0,   0]])

In [29]:
confusion_matrix(y_test, y_predik2, labels = [1,0])

array([[52,  0],
       [ 0,  0]])

In [30]:
print(classification_report(y_train, y_predik))

              precision    recall  f1-score   support

           1       0.81      1.00      0.89       168
           2       1.00      0.34      0.51        61

    accuracy                           0.83       229
   macro avg       0.90      0.67      0.70       229
weighted avg       0.86      0.83      0.79       229



In [31]:
print(classification_report(y_test, y_predik2))

              precision    recall  f1-score   support

           1       0.76      0.91      0.83        57
           2       0.44      0.20      0.28        20

    accuracy                           0.73        77
   macro avg       0.60      0.56      0.55        77
weighted avg       0.68      0.73      0.69        77



---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:
1. Bias memiliki error yang tinggi terhadap data training dan data test, sedangkan Variance memiliki error yang kecil terhadap data training tapi error besar terhadap data test
2. overfitting adalah suatu keadaan dimana suatu data itu terlalu menangkap detail - detail dan noise terhadap data training, sedangkan underfitting adalah suatu keadaan dimana model ini jelek dalam menangkap data training
3. dengan cara melakukan tuning hyperparameter terlebih dahulu untuk mendapatkan nilai dari hyperparameter yang idial
4. model yang minim error bias dan error variance
5. GridSearchcv digunakan pada saat nilai dari parameternya hanya sedikit, sedangkan RandomizedSearchCV digunakan pada saat menggunakan parameter yang cukup banyak dan juga untuk mempersingkat waktu

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [2]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [10]:
# Code here
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

x = df.drop('survival_status', axis=1)
y = df['survival_status']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=21, stratify = y)

In [25]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
model = KNeighborsClassifier()
param_grid = {'n_neighbors':np.arange(5, 30), 'weights':['distance', 'uniform']}
gscv = GridSearchCV(model, param_grid=param_grid, scoring='accuracy', cv=5)
gscv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29]),
                         'weights': ['distance', 'uniform']},
             scoring='accuracy')

In [17]:
gscv.best_params_

{'n_neighbors': 18, 'weights': 'distance'}

In [18]:
gscv.best_score_

0.7644444444444444

In [45]:
hasil_knn = gscv.predict_proba(x_test)
label_knn = gscv.classes_

In [46]:
pd.DataFrame(data=hasil_knn, columns=label_knn)

1         2
0   0.829412  0.170588
1   0.157895  0.842105
2   0.829412  0.170588
3   0.157895  0.842105
4   0.829412  0.170588
..       ...       ...
72  0.829412  0.170588
73  0.625000  0.375000
74  0.829412  0.170588
75  0.829412  0.170588
76  0.625000  0.375000

[77 rows x 2 columns]

In [28]:
from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier()
param_grid1 = {'max_depth':np.arange(2, 10), 'min_samples_leaf':np.arange(4,10), 'max_leaf_nodes':np.arange(2, 10)}
gscv = GridSearchCV(model1, param_grid=param_grid1, scoring='accuracy', cv=5)
gscv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': array([2, 3, 4, 5, 6, 7, 8, 9]),
                         'max_leaf_nodes': array([2, 3, 4, 5, 6, 7, 8, 9]),
                         'min_samples_leaf': array([4, 5, 6, 7, 8, 9])},
             scoring='accuracy')

In [29]:
gscv.best_params_

{'max_depth': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4}

In [30]:
gscv.best_score_

0.7252173913043478

In [42]:
hasil_dtc = gscv.predict_proba(x_test)

In [43]:
label_dtc = gscv.classes_

In [44]:
pd.DataFrame(data = hasil, columns=label)

1         2
0   0.829412  0.170588
1   0.157895  0.842105
2   0.829412  0.170588
3   0.157895  0.842105
4   0.829412  0.170588
..       ...       ...
72  0.829412  0.170588
73  0.625000  0.375000
74  0.829412  0.170588
75  0.829412  0.170588
76  0.625000  0.375000

[77 rows x 2 columns]